export const sampleAvailableOptions = ["Yes", "No"];
export const unitOptions = ["Box"];

export const manufacturerOptions = [
	"TANKTOP",
	"JACKET",
	"DRESS",
	"MENS HOODIE",
	"MENS SWEATSHIRT",
	"SWEATPANTS",
	"SWEATSHORTS",
	"BEDSHEETS",
	"TOWEL",
	"SKIRT",
	"TSHIRT",
	"PLAYSUIT",
	"TOP",
	"PANTS",
	"SHORT",
	"SHIRT",
	"POLO",
	"SWEATSHIRT",
	"TROUSER",
	"VEST",
	"KNITWEAR",
	"SHORTS",
	"SHIRTS",
	"HOODIE",
	"PANT",
	"MENS TSHIRT",
	"TROUSERS",
	"BODYSUIT",
	"SLIDES",
	"SNEAKERS",
	"Ralph Lauren",
	"UNBRANDED",
];

export const brandOptions = [
	"JACK&JONES",
	"BLEND",
	"BRUNO BANANI",
	"SELECTED HOMME",
	"ZARA",
	"TOMMY HILFIGER",
	"ADIDAS",
	"ONLY",
	"JDY",
	"LA DRAPE",
	"BLACK FASHION",
	"VILA",
	"BUBBLEROOM",
	"CHIARA FORTH",
	"KENZO",
	"JACK & JONES",
	"USPA",
	"VINTAGE",
	"DENIM&FLOWER",
	"DOPE",
	"MISGUIDED",
	"RALPH LAUREN",
	"SOLID",
	"11 PROJECT",
	"11PROJECT",
	"RESERVED",
	"ABERCROMBIE & FITCH",
	"A & F",
	"DEMIN & FLOWER",
	"SELECTED",
	"BOHOO",
	"T.M LEWIN",
	"CELIO",
	"D/STRUCT",
	"BRUNO",
	"ANDREW CHARLES",
	"BOOHOO",
	"BUBBLERROM",
	"NELLY",
	"FORMAL COLLECTION",
	"NASA",
	"OLD NAVY",
	"ONLY & SONS",
	"H&M",
	"HENLEY",
	"HENLEYS",
	"ONLY&SONS",
	"SUPERDRY",
	"JACK&JONES MENS JJIJEAN JJJACKET HOODIE",
	"S.OLIVER",
	"DOCKERS",
	"CASUAL FRIDAY",
	"KUBWA",
	"TRUE RELIGION",
	"BALLIANI",
	"LACOSTE",
	"NUBLIK",
	"VEST",
	"COAT",
	"JACKET",
	"POLO",
	"PARFOIS",
	"AEROPOSTALE",
	"ARROW",
	"SOUTHWEST",
	"CROPP",
	"PIECES",
	"ROXY",
	"VOIJEANS",
	"SEMIR",
	"JXCARLA",
	"MISS SIXTY",
	"VEROMODA",
	"PLT",
	"SPRINGFIELD",
	"JEFFERSON",
	"REEBOK",
	"SIGNATURE",
	"PRODUKT",
	"MONTEC",
	"ASOS",
	"SAINSBURY",
	"NEW LOOK",
	"BALENCIAGA",
	"POLO RALPH",
	"NIKE",
	"UNDER ARMOUR",
	"UNIPRO",
	"VOI",
	"LEGEND",
	"BROOKYLN",
	"RBX",
	"GUCCI",
	"NINE WEST",
	"YOURS",
	"AIR",
	"NEW ERA",
	"DSTRUCT",
	"NEW LOOKS",
	"SELECTED FEMME",
	"MITRE",
	"PUMA",
	"AFA",
	"MARKS & SPENCER",
	"LEVI",
	"TOMMY",
	"SLECTED",
	"MOSS",
	"DREESMAN",
	"CHARLES",
	"DRESSMANN & COTTON",
	"NICOLE GIOVANNI",
	"ROBERT GRAHAM",
	"PERRY ELIS",
	"ROYAL",
	"GREEN",
	"ROSE",
	"CHLOE",
	"	DEEPRIO & INCH",
	"DEEPRIO",
	"HEADWATCH",
	"VOYAGE",
	"GODDIVA",
	"DAD",
	"SISTERS",
	"CALZEDONIA",
	"NOISY MAY",
	"HOLLY",
	"TEZENIS",
	"VERO",
	"PRETTY & THING",
	"ONLY & BOXY",
	"	JJXX",
	"BLACK",
	"JACK",
	"TRIAL",
	"I SOLID",
	"BURTON",
	"DENIM & FLOWER",
	"PRADA",
	"BOOHOOMAN",
	"CASUAL",
	"BLEND & STRIPE",
	"MENNACE",
	"JACK & JONE",
	"	BOHEMIAN",
	"BRUNO BABANI",
	"CALVIN KLEIN",
	"CHIARA",
	"D.A.D",
	"GABBA",
	"GRAPHIX",
	"GRIZZLY",
	"HAPPY HOLLY",
	"INTELLIGENTSTORE",
	"JOLLY HOLLA",
	"KIDDIES",
	"MAESTRO",
	"MARKS&SPENCE",
	"MICHEAL KORS",
	"MISGUDIED",
	"	MISSGUIDED",
	"NO PROBLEM",
	"OLD",
	"ONLY AND SONS",
	"ONLY&SON",
	"PORFOIS",
	"SISTER POINT",
	"LODING",
	"PRETTY LITTLE THINGS",
	"PARAGON",
	"SPRINGFILED",
	"HARMONTH&BLAINE",
	"JOE BROWN",
	"TUMAN",
	"INTELLIEGIENT",
	"JOHN ZACK",
	"ANGEL EYE",
	"F&P",
	"JOOP",
	"SISTERS POINT",
	"RARE RABBIT",
	"THESE GLORY DAYS",
	"ENGLISH LAUNDRY",
	"COLE HAAN",
	"PULL&BEAR",
	"PANTALON",
	"GREGNORMAN",
	"HURLEY",
	"LYLE & SCOTT",
	"LEVI'S",
	"GILDAN",
	"NASTY",
	"THESE GLORY",
	"JARGER",
	"MESOS",
	"REISS",
	"FURSAC",
	"CHARLES TYRWHITT",
	"HARMONTE&BLAINE",
	"TRACKER",
	"CUTTER&BUCK",
	"TM LEWIN",
	"HARMONT & BLAINE",
	"JAEGER",
	"MB",
	"MANGO",
	"REDGREEN",
	"STEVE MADDEN",
	"GARANT",
	"TOMMY HILFILGER",
	"BELLFIELD",
	"BELLFIELD MENS",
	"GOLDEN EQUATION",
	"GUESS",
	"BERSHKA",
	"TCA",
	"COLLUSION",
	"SMILA",
	"BOOHO MAN",
	"SPLASH",
	"DOLCE&GABBANA",
	"FENDI",
	"HERMES",
	"QUIZ",
	"YOURSCLOTHING",
	"LTS",
	"TINSEL",
	"NASTY GAL",
	"INFLUENCE MEN",
	"RIVER ISL",
	"TEXAS MEN",
	"B&C MEN",
	"MOUNTAIN WAR",
	"ISAW IT FISRT",
	"BOOHO",
	"STEINBECK",
	"ODEVAL",
	"GEORGE UK",
	"RIVERS ISLAND",
	"TU MAN",
	"LE SHARK",
	"U.S. POLO ASSN",
	"HUMMEL",
	"	LONG TALL",
	"ADPT",
	"JACK&JONE",
	"DICKIES",
	"TRUERELIGION",
	"COLUMBIA",
	"PIER ONE",
	"MEROK",
	"EVERLAST",
	"LONSDALE",
	"EX NEXT",
	"MARKS AND SPENCER",
	"LESHARK",
	"GOODFELLOW",
	"TOKYO LAUNDRY",
	"NAUTICA",
	"U.S POLO ASSN",
	"PIERRE CARDIN",
	"CARHARTT",
	"LUMIERE",
	"NOEXCESS",
	"TAILOR VINTAGE",
	"BOOHOOWOMAN",
	"PULL & BEAR",
	"POKEMON",
	"GIRLS PAW PATROL",
	"SELECTED/ ZARA",
	"BUBBLEROON",
	"GOTCHA",
	"PLL&BEAR",
	"ONY &SONS",
	"BLACK DRESS",
	"JJ",
	"CELINE",
	"DIOR",
	"DISQUARES",
	"BURBERRY",
	"AMIRI",
	"STONE ISLAND",
	"PRINT",
	"RIVER ISLAND",
	"OLIVER",
	"LIQUORISH",
	"MAXI",
	"VENDORA",
	"MATALAN",
	"PRIMARK",
	"BOOHOO MAN",
	"MISS SELFRIDGE",
	"PRETTY",
	"PIXIEGIRL",
	"TOPMAN",
	"ANOTHER INFLUENCE",
	"I SAW IT FIRST",
	"LVRS",
	"DUMA",
	"NORTH WEST",
	"LIMITED COLLECTION",
	"LONDON WOMEN",
	"BOOHOO/BURTON",
	"PIXELGIRL",
	"BOSS",
	"TIMBERLAND",
	"TOMMY HILL FINGER",
	"JACK &JONES",
	"LONDON CREW",
	"LIQUOR & POKER",
	"WESSI",
	"NORTHWEST",
	"RIVERISLAND",
	"TOPSHOP",
	"BURNT",
	"SELFRIDGE",
	"RAID",
	"INFLUENCE",
	"DENIM",
	"KAPPA",
	"CLASSIC",
	"RUSSELL",
	"ASYOU",
	"PARISIAN",
	"MISS",
	"TOPSHPO",
	"REBELLIOUS",
	"PUBLIC",
	"BRAVE",
	"QED",
	"EXTRO",
	"LOLA",
	"ANOTHER",
	"NEXT",
	"MORGAN",
	"HILLT",
	"I SAW",
	"DAISY STREET",
	"HIIT",
	"LONDON",
	"BYRNE",
	"BOWIE",
	"RED",
	"DAISY",
	"ROKWEAR",
	"VELTUFF",
	"REGATTA",
	"ALEXANDRA",
	"RYT",
	"HENBURY",
	"CADENZA",
	"SPRNGFIELD",
	"SPINGFIELD",
	"BALANCIAGA",
	"SANSBURY",
	"SINGATURE",
	"LYTE& SCOA",
	"STUDIO",
	"	BILL PETE",
	"NEWLOOK",
	"NELY",
	"HAPPY",
	"SIMSAY",
	"ISOLDI",
	"VILLA",
	"BLACK BLUE",
	"PULL&BEAR/ZARA",
	"GIOVANNI",
	"HOUSE BRAND",
	"TENZO",
	"F & P",
	"HACKETT LONDON",
	"DEMIN & FLOlWER",
	"T.M",
	"GLORY DAYS",
	"FRED PERRY",
	"DEMIN &FLOWER",
	"POLO BY RALPH",
	"JOEBROWN",
	"TEXAS",
	"NOVAMEN",
	"ADPTBWO",
	"ADPTSAP",
	"ADPTMAH",
	"MARK & SPENCER",
	"PIER",
	"I SAW IT",
	"JOYSPUN",
	"JUSTIC DANCE",
	"MG",
	"PRETTYLITHING",
	"ADPTDLN",
	"CHIARA FORTHI",
	"MOUNTAIN",
	"B&C",
	"TNCTEX",
	"CLUB",
	"MONKI",
	"LINDEX",
	"BLUEBELLA",
	"	EVRLAST UOMO",
	"CLUE LONDON",
	"PRETTYLITTLETHING",
	"REPLAY",
	"RECLAMER",
	"COSMOGONIE",
	"LONDALE",
	"ALLSAINTS",
	"CLLOUSION",
	"4TH RECKLESS",
	"MISSYEMPIRE",
	"ANNORLUNDA",
	"FILA",
	"SELECT",
	"LINEN LOOK",
	"NAANAA",
	"FIRST",
	"LITTLE",
	"GLAMOROUS",
	"FEMME",
	"COLLECTION",
	"DON'T THINK",
	"WHISTLES",
	"CROPPED",
	"CLUB ANGELIO",
	"REEBOX",
	"CALVIN",
	"TRENDYOL",
	"Kappa",
	"T.M.LEWIN",
	"HARMONT",
	"MB BISHOP",
	"GREGONRMAN",
	"HRF",
	"FAUITLESS SPARKLES",
	"FAULTLESS SPARKLES",
	"Nigeria Brands",
	"UK/US Brands",
	"CORD",
	"CLUBLONDON",
	"nige",
	"JOOP!",
	"SMT",
	"Hackett",
	"LYLE&SCOTT",
	"Wrangler",
	"Coca Cola",
	"UNBRANDED",
	"Remy",
	"DEVAL",
	"MO",
	"SCHMUDDELVEDDA",
	"TUFFSKULL",
	"CREST DEPT",
	"POLO RALPH LAUREN",
	"I SAW FIRST",
	"HUDSON & BARROW",
];

export const incotermsOptions = ["EXW", "FOB / FAS", " DAP / DDP", "CIP / CIF"];

export const fobOptions = [
	"Lagos - Nigeria",
	"London - UK",
	"Mumbai - india",
	"New York - USA",
	"Paris - France",
	"Singapore - Singapore",
	"Tokyo - Japan",
	"Washington DC - USA",
	"Guangzhou - China",
	"Berlin - Germany",
	"Istanbul - Turkey",
	"Barcelona - Spain",
	"Sydney - Australia",
	"Melbourne - Australia",
	"Beijing - China",
	"Bangkok - Thailand",
	"Nairobi - Kenya",
];

export const fabricTypeOptions = [
	"Cotton",
	"Polyester",
	"Wool",
	"Silk",
	"Linen",
	"Leather",
	"Chiffon",
	"Crepe",
];
// const sizeTypeOptions = ["Small", "Medium", "Large", "X-Large", "XX-Large"];
export const unitPerBoxOptions = [
	"5",
	"6",
	"7",
	"8",
	"9",
	"10",
	"12",
	"15",
	"20",
	"25",
	"30",
	"50",
];

export const availableColorOptions = [
	"Mixed Colors",
	"White",
	"Black",
	"Grey",
	"Navy Blue",
	"Brown",
	"Red",
	"Royal Blue",
	"Yellow",
	"Green (Olive or Forest)",
	"Pink (Blush or Hot Pink)",
	"Orange (Burnt Orange)",
	"Purple (Lavender or Plum)",
	"Beige",
	"Maroon",
	"Khaki",
];

interface SizeTypeOption {
	type: string;
	categories: {
		name: string;
		subcategories: {
			name: string;
			sizes: string[];
		}[];
	}[];
}

export const sizeTypeOptions: SizeTypeOption[] = [
	{
		type: "Apparel",
		categories: [
			{
				name: "Men's",
				subcategories: [
					{ name: "Shirts", sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL"] },
					{ name: "T-Shirts", sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL"] },
					{ name: "Pants", sizes: ["28", "30", "32", "34", "36", "38", "40", "42", "44"] },
					{ name: "Shorts", sizes: ["S", "M", "L", "XL", "2XL"] },
					{ name: "Jackets/Coats", sizes: ["S", "M", "L", "XL", "2XL", "3XL"] },
					{ name: "Sweaters", sizes: ["S", "M", "L", "XL", "2XL"] },
					{ name: "Suits", sizes: ["36", "38", "40", "42", "44", "46", "48"] },
					{ name: "Vests", sizes: ["S", "M", "L", "XL", "2XL"] },
					{ name: "Polos", sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"] },
					{ name: "Tracksuits", sizes: ["S", "M", "L", "XL", "2XL"] },
				],
			},
			{
				name: "Women's",
				subcategories: [
					{ name: "Dresses", sizes: ["6", "8", "10", "12", "14", "16", "18", "20", "22"] },
					{ name: "Tops", sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"] },
					{ name: "Skirts", sizes: ["6", "8", "10", "12", "14", "16", "18", "20"] },
					{ name: "Pants", sizes: ["6", "8", "10", "12", "14", "16", "18", "20", "22"] },
					{ name: "Shorts", sizes: ["XS", "S", "M", "L", "XL"] },
					{ name: "Jackets/Coats", sizes: ["XS", "S", "M", "L", "XL", "2XL"] },
					{ name: "Blouses", sizes: ["XS", "S", "M", "L", "XL", "2XL"] },
					{ name: "Tunic Tops", sizes: ["XS", "S", "M", "L", "XL"] },
					{ name: "Leggings", sizes: ["XS", "S", "M", "L", "XL", "2XL"] },
					{ name: "Cardigans", sizes: ["XS", "S", "M", "L", "XL", "2XL"] },
				],
			},
			{
				name: "Unisex",
				subcategories: [
					{ name: "Hoodies", sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"] },
					{ name: "Sweatshirts", sizes: ["XS", "S", "M", "L", "XL", "2XL"] },
					{ name: "Ponchos", sizes: ["S", "M", "L", "XL"] },
					{ name: "Kimono Jackets", sizes: ["S", "M", "L", "XL"] },
				],
			},
		],
	},
	{
		type: "Shoes",
		categories: [
			{
				name: "Men's Shoes",
				subcategories: [
					{
						name: "Casual Shoes/Boots",
						sizes: ["7", "8", "9", "10", "11", "12", "13", "14"],
					},
					{ name: "Dress Shoes", sizes: ["7", "8", "9", "10", "11", "12", "13"] },
					{ name: "Sports Shoes", sizes: ["7", "8", "9", "10", "11", "12", "13", "14"] },
					{ name: "Sandals/Flip Flops", sizes: ["7", "8", "9", "10", "11", "12"] },
				],
			},
			{
				name: "Women's Shoes",
				subcategories: [
					{ name: "Flats", sizes: ["5", "6", "7", "8", "9", "10", "11", "12"] },
					{ name: "Heels", sizes: ["5", "6", "7", "8", "9", "10", "11", "12"] },
					{ name: "Boots", sizes: ["5", "6", "7", "8", "9", "10", "11", "12"] },
					{ name: "Sports Shoes", sizes: ["5", "6", "7", "8", "9", "10", "11", "12"] },
					{ name: "Sandals/Flip Flops", sizes: ["5", "6", "7", "8", "9", "10", "11"] },
				],
			},
			{
				name: "Unisex Shoes",
				subcategories: [
					{ name: "Slippers", sizes: ["5", "6", "7", "8", "9", "10", "11", "12", "13"] },
					{ name: "Sneakers", sizes: ["7", "8", "9", "10", "11", "12"] },
				],
			},
		],
	},
	{
		type: "Accessories",
		categories: [
			{
				name: "Hats/Headwear",
				subcategories: [
					{ name: "Baseball Caps", sizes: ["One Size", "S/M", "M/L", "L/XL"] },
					{ name: "Beanies", sizes: ["One Size"] },
					{ name: "Fedoras", sizes: ["S", "M", "L", "XL"] },
					{ name: "Bucket Hats", sizes: ["One Size"] },
					{ name: "Sun Hats", sizes: ["One Size", "S/M", "M/L", "L/XL"] },
				],
			},
			{
				name: "Gloves",
				subcategories: [
					{ name: "Winter Gloves", sizes: ["S", "M", "L", "XL"] },
					{ name: "Leather Gloves", sizes: ["S", "M", "L", "XL"] },
					{ name: "Sports Gloves", sizes: ["S", "M", "L", "XL"] },
					{ name: "Fingerless Gloves", sizes: ["S", "M", "L", "XL"] },
				],
			},
			// Add other accessories categories as needed
		],
	},
];
